# Generated by Django 5.0.3 on 2025-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lesson_date_alter_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
