# Generated by Django 5.0.3 on 2025-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('allDay', models.BooleanField(default=False)),
            ],
        ),
    ]
