# Generated by Django 5.0.3 on 2025-04-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studioevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioevent',
            name='end',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
